name: Bug Report
description: Report a bug in OpenMBU+
title: "[BUG] "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      If you have a question or need help, proceed here:
      OpenMBU+ Discord (#help) - https://discord.gg/MxxMMwB3RN
      Otherwise make a bug report
      
      Try to create a very concise title that's straight to the point
      ##
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Version
    description: What version are you running?
    multiple: false
    options:
      - 1.0.0 Beta 1
      - Self-Compiled (please specify branch)
      - Other (please specify elsewhere)
  validations:
    required: true
- type: dropdown
  attributes:
    label: OS
    description: What OS are you on?
    multiple: false
    options:
      - Windows 11
      - Windows 10
      - Windows 8.1 (Not Supported)
      - Windows 8 (Not Supported)
      - Windows 7 (Not Supported)
      - Windows Vista (Not Supported)
      - Windows XP (Not Supported)
      - Linux (Proton)
      - Linux (Wine)
      - Linux (Native)
      - MacOS (Not Supported)
  validations:
    required: true  
- type: textarea
  attributes:
    label: Description
    id: description
    description: |
      Describe your issue(s) here. What is the issue?
      Please keep this as concise as possible, preferably a single line describing the issue. 
      For example: "When I press X button in menu Y, the component Z becomes unclickable"
- type: textarea
  attributes:
    label: Log File
    description: |
      Please attach the `console.log` file here. You'll find the log file in the folder where the game is installed, if it's not there, it's because your running the game from a protected location such as ``C:\Program Files\OpenMBU`` and we don't recommend that. 
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please describe the steps to reproduce this issue
    placeholder: |
      1. [First Step]
      2. [Second Step]
      3. [And so on...]
- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      What should be happening? If you don't know, leave what you think should happen
- type: textarea
  attributes:
    label: Actual Behavior
    description: |
      What is actually happening?
- type: textarea
  attributes:
    label: Reproduction frequency
    description: |
      How often are you reliably able to reproduce this issue?
- type: textarea
  attributes:
    label: Additional Information
    description: |
       Any additional information, configuration, or data that might be necessary to reproduce the issue.
